[versions]
spring-boot = "4.0.3"
spring-dependency-management = "1.1.7"
springdoc = "3.0.2"
springwolf = "2.1.0"
lombok = "1.18.42"
spotless = "7.2.1"
license-report = "3.1.1"
graalvm-native = "0.11.1"
checkstyle = "12.1.1"
jacoco = "0.8.12"
versions = "0.53.0"
opentelemetry-bom = "1.56.0"
protobuf = "4.33.1"
jobrunr = "8.5.0"

[libraries]
springdoc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springwolfstomp = { module = "io.github.springwolf:springwolf-stomp", version.ref = "springwolf" }
springwolfstompbinding = { module = "io.github.springwolf:springwolf-stomp-binding", version.ref = "springwolf" }
springwolfui = { module = "io.github.springwolf:springwolf-ui", version.ref = "springwolf" }
opentelemetrybom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry-bom" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
jobrunr = { module = "org.jobrunr:jobrunr-spring-boot-4-starter", version.ref = "jobrunr" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "license-report" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
